package com.honglu.quickcall.account.service.dao;

import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.honglu.quickcall.account.facade.entity.ChannelSwitch;

public interface ChannelSwitchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_switch
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_switch
     *
     * @mbg.generated
     */
    int insert(ChannelSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_switch
     *
     * @mbg.generated
     */
    int insertSelective(ChannelSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_switch
     *
     * @mbg.generated
     */
    ChannelSwitch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_switch
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChannelSwitch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_switch
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChannelSwitch record);
    
    /**
     * 根据渠道和版本获取状态
     * @param channel
     * @param version
     * @return
     */
    Integer getChannelSwitchStatusByCV (@Param("channel") String channel,@Param("version") String version);
}