package com.honglu.quickcall.user.facade.entity;

import java.util.Date;

public class AppShareConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share_config.id
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share_config.title
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share_config.content
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share_config.icon_url
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    private String iconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share_config.link_url
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    private String linkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share_config.type
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share_config.create_time
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share_config.modify_time
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share_config.create_man
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share_config.modify_man
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    private String modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share_config.remark
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share_config.id
     *
     * @return the value of app_share_config.id
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share_config.id
     *
     * @param id the value for app_share_config.id
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share_config.title
     *
     * @return the value of app_share_config.title
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share_config.title
     *
     * @param title the value for app_share_config.title
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share_config.content
     *
     * @return the value of app_share_config.content
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share_config.content
     *
     * @param content the value for app_share_config.content
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share_config.icon_url
     *
     * @return the value of app_share_config.icon_url
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share_config.icon_url
     *
     * @param iconUrl the value for app_share_config.icon_url
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share_config.link_url
     *
     * @return the value of app_share_config.link_url
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share_config.link_url
     *
     * @param linkUrl the value for app_share_config.link_url
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share_config.type
     *
     * @return the value of app_share_config.type
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share_config.type
     *
     * @param type the value for app_share_config.type
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share_config.create_time
     *
     * @return the value of app_share_config.create_time
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share_config.create_time
     *
     * @param createTime the value for app_share_config.create_time
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share_config.modify_time
     *
     * @return the value of app_share_config.modify_time
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share_config.modify_time
     *
     * @param modifyTime the value for app_share_config.modify_time
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share_config.create_man
     *
     * @return the value of app_share_config.create_man
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share_config.create_man
     *
     * @param createMan the value for app_share_config.create_man
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share_config.modify_man
     *
     * @return the value of app_share_config.modify_man
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public String getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share_config.modify_man
     *
     * @param modifyMan the value for app_share_config.modify_man
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan == null ? null : modifyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share_config.remark
     *
     * @return the value of app_share_config.remark
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share_config.remark
     *
     * @param remark the value for app_share_config.remark
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}