package com.honglu.quickcall.user.facade.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BigvSkillScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bigv_skill_score.id
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bigv_skill_score.customer_id
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bigv_skill_score.skill_item_id
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    private Long skillItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bigv_skill_score.order_total
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    private Integer orderTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bigv_skill_score.score_total
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    private BigDecimal scoreTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bigv_skill_score.create_time
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bigv_skill_score.modify_time
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bigv_skill_score.create_man
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bigv_skill_score.modify_man
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    private String modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bigv_skill_score.remark
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bigv_skill_score.id
     *
     * @return the value of bigv_skill_score.id
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bigv_skill_score.id
     *
     * @param id the value for bigv_skill_score.id
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bigv_skill_score.customer_id
     *
     * @return the value of bigv_skill_score.customer_id
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bigv_skill_score.customer_id
     *
     * @param customerId the value for bigv_skill_score.customer_id
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bigv_skill_score.skill_item_id
     *
     * @return the value of bigv_skill_score.skill_item_id
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public Long getSkillItemId() {
        return skillItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bigv_skill_score.skill_item_id
     *
     * @param skillItemId the value for bigv_skill_score.skill_item_id
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public void setSkillItemId(Long skillItemId) {
        this.skillItemId = skillItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bigv_skill_score.order_total
     *
     * @return the value of bigv_skill_score.order_total
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public Integer getOrderTotal() {
        return orderTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bigv_skill_score.order_total
     *
     * @param orderTotal the value for bigv_skill_score.order_total
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public void setOrderTotal(Integer orderTotal) {
        this.orderTotal = orderTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bigv_skill_score.score_total
     *
     * @return the value of bigv_skill_score.score_total
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public BigDecimal getScoreTotal() {
        return scoreTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bigv_skill_score.score_total
     *
     * @param scoreTotal the value for bigv_skill_score.score_total
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public void setScoreTotal(BigDecimal scoreTotal) {
        this.scoreTotal = scoreTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bigv_skill_score.create_time
     *
     * @return the value of bigv_skill_score.create_time
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bigv_skill_score.create_time
     *
     * @param createTime the value for bigv_skill_score.create_time
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bigv_skill_score.modify_time
     *
     * @return the value of bigv_skill_score.modify_time
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bigv_skill_score.modify_time
     *
     * @param modifyTime the value for bigv_skill_score.modify_time
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bigv_skill_score.create_man
     *
     * @return the value of bigv_skill_score.create_man
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bigv_skill_score.create_man
     *
     * @param createMan the value for bigv_skill_score.create_man
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bigv_skill_score.modify_man
     *
     * @return the value of bigv_skill_score.modify_man
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public String getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bigv_skill_score.modify_man
     *
     * @param modifyMan the value for bigv_skill_score.modify_man
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan == null ? null : modifyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bigv_skill_score.remark
     *
     * @return the value of bigv_skill_score.remark
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bigv_skill_score.remark
     *
     * @param remark the value for bigv_skill_score.remark
     *
     * @mbggenerated Thu Oct 25 14:43:15 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}