package com.honglu.quickcall.user.facade.entity;

import java.util.Date;

public class BigvPhone {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column bigv_phone.id
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column bigv_phone.phone
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	private Long phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column bigv_phone.create_time
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column bigv_phone.modify_time
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	private Date modifyTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column bigv_phone.create_man
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	private String createMan;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column bigv_phone.modify_man
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	private String modifyMan;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column bigv_phone.remark
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column bigv_phone.id
	 *
	 * @return the value of bigv_phone.id
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column bigv_phone.id
	 *
	 * @param id
	 *            the value for bigv_phone.id
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column bigv_phone.phone
	 *
	 * @return the value of bigv_phone.phone
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public Long getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column bigv_phone.phone
	 *
	 * @param phone
	 *            the value for bigv_phone.phone
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public void setPhone(Long phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column bigv_phone.create_time
	 *
	 * @return the value of bigv_phone.create_time
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column bigv_phone.create_time
	 *
	 * @param createTime
	 *            the value for bigv_phone.create_time
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column bigv_phone.modify_time
	 *
	 * @return the value of bigv_phone.modify_time
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column bigv_phone.modify_time
	 *
	 * @param modifyTime
	 *            the value for bigv_phone.modify_time
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column bigv_phone.create_man
	 *
	 * @return the value of bigv_phone.create_man
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public String getCreateMan() {
		return createMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column bigv_phone.create_man
	 *
	 * @param createMan
	 *            the value for bigv_phone.create_man
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public void setCreateMan(String createMan) {
		this.createMan = createMan == null ? null : createMan.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column bigv_phone.modify_man
	 *
	 * @return the value of bigv_phone.modify_man
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public String getModifyMan() {
		return modifyMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column bigv_phone.modify_man
	 *
	 * @param modifyMan
	 *            the value for bigv_phone.modify_man
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public void setModifyMan(String modifyMan) {
		this.modifyMan = modifyMan == null ? null : modifyMan.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column bigv_phone.remark
	 *
	 * @return the value of bigv_phone.remark
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column bigv_phone.remark
	 *
	 * @param remark
	 *            the value for bigv_phone.remark
	 *
	 * @mbggenerated Sat Nov 03 10:47:50 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}