package com.honglu.quickcall.user.facade.entity;

import java.util.Date;

public class Blacklist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.id
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.customer_id
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.black_customer_id
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    private Long blackCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.status
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.create_time
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.modify_time
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.create_man
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.modify_man
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    private String modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.remark
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.id
     *
     * @return the value of blacklist.id
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.id
     *
     * @param id the value for blacklist.id
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.customer_id
     *
     * @return the value of blacklist.customer_id
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.customer_id
     *
     * @param customerId the value for blacklist.customer_id
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.black_customer_id
     *
     * @return the value of blacklist.black_customer_id
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public Long getBlackCustomerId() {
        return blackCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.black_customer_id
     *
     * @param blackCustomerId the value for blacklist.black_customer_id
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public void setBlackCustomerId(Long blackCustomerId) {
        this.blackCustomerId = blackCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.status
     *
     * @return the value of blacklist.status
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.status
     *
     * @param status the value for blacklist.status
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.create_time
     *
     * @return the value of blacklist.create_time
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.create_time
     *
     * @param createTime the value for blacklist.create_time
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.modify_time
     *
     * @return the value of blacklist.modify_time
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.modify_time
     *
     * @param modifyTime the value for blacklist.modify_time
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.create_man
     *
     * @return the value of blacklist.create_man
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.create_man
     *
     * @param createMan the value for blacklist.create_man
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.modify_man
     *
     * @return the value of blacklist.modify_man
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public String getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.modify_man
     *
     * @param modifyMan the value for blacklist.modify_man
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan == null ? null : modifyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.remark
     *
     * @return the value of blacklist.remark
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.remark
     *
     * @param remark the value for blacklist.remark
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}