package com.honglu.quickcall.user.facade.entity;

import java.util.Date;

/**
 * 用户访问表
 * @author zhaozheyi
 *
 */
public class CustomerVisit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_visit.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_visit.visitor_id
     *
     * @mbg.generated
     */
    private Long visitorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_visit.interviewee_id
     *
     * @mbg.generated
     */
    private Long intervieweeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_visit.visit_path
     *
     * @mbg.generated
     */
    private Byte visitPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_visit.read_status
     *
     * @mbg.generated
     */
    private Byte readStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_visit.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_visit.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_visit.create_man
     *
     * @mbg.generated
     */
    private String createMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_visit.modify_man
     *
     * @mbg.generated
     */
    private String modifyMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_visit.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_visit.id
     *
     * @return the value of customer_visit.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_visit.id
     *
     * @param id the value for customer_visit.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_visit.visitor_id
     *
     * @return the value of customer_visit.visitor_id
     *
     * @mbg.generated
     */
    public Long getVisitorId() {
        return visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_visit.visitor_id
     *
     * @param visitorId the value for customer_visit.visitor_id
     *
     * @mbg.generated
     */
    public void setVisitorId(Long visitorId) {
        this.visitorId = visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_visit.interviewee_id
     *
     * @return the value of customer_visit.interviewee_id
     *
     * @mbg.generated
     */
    public Long getIntervieweeId() {
        return intervieweeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_visit.interviewee_id
     *
     * @param intervieweeId the value for customer_visit.interviewee_id
     *
     * @mbg.generated
     */
    public void setIntervieweeId(Long intervieweeId) {
        this.intervieweeId = intervieweeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_visit.visit_path
     *
     * @return the value of customer_visit.visit_path
     *
     * @mbg.generated
     */
    public Byte getVisitPath() {
        return visitPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_visit.visit_path
     *
     * @param visitPath the value for customer_visit.visit_path
     *
     * @mbg.generated
     */
    public void setVisitPath(Byte visitPath) {
        this.visitPath = visitPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_visit.read_status
     *
     * @return the value of customer_visit.read_status
     *
     * @mbg.generated
     */
    public Byte getReadStatus() {
        return readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_visit.read_status
     *
     * @param readStatus the value for customer_visit.read_status
     *
     * @mbg.generated
     */
    public void setReadStatus(Byte readStatus) {
        this.readStatus = readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_visit.create_time
     *
     * @return the value of customer_visit.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_visit.create_time
     *
     * @param createTime the value for customer_visit.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_visit.modify_time
     *
     * @return the value of customer_visit.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_visit.modify_time
     *
     * @param modifyTime the value for customer_visit.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_visit.create_man
     *
     * @return the value of customer_visit.create_man
     *
     * @mbg.generated
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_visit.create_man
     *
     * @param createMan the value for customer_visit.create_man
     *
     * @mbg.generated
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_visit.modify_man
     *
     * @return the value of customer_visit.modify_man
     *
     * @mbg.generated
     */
    public String getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_visit.modify_man
     *
     * @param modifyMan the value for customer_visit.modify_man
     *
     * @mbg.generated
     */
    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan == null ? null : modifyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_visit.remark
     *
     * @return the value of customer_visit.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_visit.remark
     *
     * @param remark the value for customer_visit.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}