package com.honglu.quickcall.activity.service.dao;

import com.honglu.quickcall.activity.facade.entity.CouponSkill;

public interface CouponSkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_skill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_skill
     *
     * @mbggenerated
     */
    int insert(CouponSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_skill
     *
     * @mbggenerated
     */
    int insertSelective(CouponSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_skill
     *
     * @mbggenerated
     */
    CouponSkill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_skill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CouponSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_skill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CouponSkill record);
}