package com.honglu.quickcall.activity.service.dao;

import com.honglu.quickcall.activity.facade.entity.CustomerCoupon;
import org.apache.ibatis.annotations.Param;

import java.util.Map;

public interface CustomerCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon
     *
     * @mbggenerated
     */
    int insert(CustomerCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon
     *
     * @mbggenerated
     */
    int insertSelective(CustomerCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon
     *
     * @mbggenerated
     */
    CustomerCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerCoupon record);

    int selectByCustomerIdAndCouponId(Map<String,String> map);

    CustomerCoupon queryCustomerCouponByCustomerIdAndOrderId(@Param("customerId") Long customerId, @Param("orderId") Long orderId);

    int cancelUpdateCustomerCoupon(@Param("id") Integer id);
}