package com.honglu.quickcall.activity.service.dao;

import com.honglu.quickcall.activity.facade.entity.CustomerCoupon;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CustomerCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon
     *
     * @mbggenerated
     */
    int insert(CustomerCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon
     *
     * @mbggenerated
     */
    int insertSelective(CustomerCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon
     *
     * @mbggenerated
     */
    CustomerCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_coupon
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerCoupon record);

    int selectByCustomerIdAndCouponId(Map<String,String> map);

    /**
     * 根据订单ID查询客户优惠券
     * @return
     */
    Map<String,String> getCustomerCouponByOrderId(@Param("orderId")Long orderId);

    /**
     * 查询券
     * @return
     */
    String getCouponIdBySkillItemId(@Param("list") List<String> statusList);

    /**
     * 查询是否展示提示
     * @return
     */
    int getShowTip(@Param("couponId")String couponId ,@Param("customerId")String customerId);


    CustomerCoupon queryCustomerCouponByCustomerIdAndOrderId(@Param("customerId") Long customerId, @Param("orderId") Long orderId);

    int cancelUpdateCustomerCoupon(@Param("id") Integer id);

    /**
     * 根据券ID查活动名字和券名字
     * @param couponId
     * @return
     */
    Map<String,String> selectActivityNameAndCouponName(@Param("couponId")Long couponId);

}