package com.calf.module.activity.entity;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_id
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    private String activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_name
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_code
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    private String activityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.start_time
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_time
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.create_time
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.modify_time
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.create_man
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.modify_man
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    private String modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.remark
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_id
     *
     * @return the value of activity.activity_id
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_id
     *
     * @param activityId the value for activity.activity_id
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_name
     *
     * @return the value of activity.activity_name
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_name
     *
     * @param activityName the value for activity.activity_name
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_code
     *
     * @return the value of activity.activity_code
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public String getActivityCode() {
        return activityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_code
     *
     * @param activityCode the value for activity.activity_code
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public void setActivityCode(String activityCode) {
        this.activityCode = activityCode == null ? null : activityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_time
     *
     * @return the value of activity.start_time
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_time
     *
     * @param startTime the value for activity.start_time
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_time
     *
     * @return the value of activity.end_time
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_time
     *
     * @param endTime the value for activity.end_time
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.create_time
     *
     * @return the value of activity.create_time
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.create_time
     *
     * @param createTime the value for activity.create_time
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.modify_time
     *
     * @return the value of activity.modify_time
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.modify_time
     *
     * @param modifyTime the value for activity.modify_time
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.create_man
     *
     * @return the value of activity.create_man
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.create_man
     *
     * @param createMan the value for activity.create_man
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.modify_man
     *
     * @return the value of activity.modify_man
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public String getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.modify_man
     *
     * @param modifyMan the value for activity.modify_man
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan == null ? null : modifyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.remark
     *
     * @return the value of activity.remark
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.remark
     *
     * @param remark the value for activity.remark
     *
     * @mbggenerated Tue Oct 30 14:55:30 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}