package com.calf.module.activity.entity;

import java.util.Date;

public class Ticket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_id
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private String ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_name
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private String ticketName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.is_permanent
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private Integer isPermanent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_type
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private Integer ticketType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.start_time
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.end_time
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.acitivity_id
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private Integer acitivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_price
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private Integer ticketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.create_time
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.modify_time
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.create_man
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.modify_man
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private String modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.remark
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    private String remark;


    private String ticketCode;

    public String getTicketCode() {
        return ticketCode;
    }

    public void setTicketCode(String ticketCode) {
        this.ticketCode = ticketCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_id
     *
     * @return the value of ticket.ticket_id
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public String getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_id
     *
     * @param ticketId the value for ticket.ticket_id
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_name
     *
     * @return the value of ticket.ticket_name
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public String getTicketName() {
        return ticketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_name
     *
     * @param ticketName the value for ticket.ticket_name
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setTicketName(String ticketName) {
        this.ticketName = ticketName == null ? null : ticketName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.is_permanent
     *
     * @return the value of ticket.is_permanent
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public Integer getIsPermanent() {
        return isPermanent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.is_permanent
     *
     * @param isPermanent the value for ticket.is_permanent
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setIsPermanent(Integer isPermanent) {
        this.isPermanent = isPermanent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_type
     *
     * @return the value of ticket.ticket_type
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public Integer getTicketType() {
        return ticketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_type
     *
     * @param ticketType the value for ticket.ticket_type
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setTicketType(Integer ticketType) {
        this.ticketType = ticketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.start_time
     *
     * @return the value of ticket.start_time
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.start_time
     *
     * @param startTime the value for ticket.start_time
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.end_time
     *
     * @return the value of ticket.end_time
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.end_time
     *
     * @param endTime the value for ticket.end_time
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.acitivity_id
     *
     * @return the value of ticket.acitivity_id
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public Integer getAcitivityId() {
        return acitivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.acitivity_id
     *
     * @param acitivityId the value for ticket.acitivity_id
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setAcitivityId(Integer acitivityId) {
        this.acitivityId = acitivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_price
     *
     * @return the value of ticket.ticket_price
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public Integer getTicketPrice() {
        return ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_price
     *
     * @param ticketPrice the value for ticket.ticket_price
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setTicketPrice(Integer ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.create_time
     *
     * @return the value of ticket.create_time
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.create_time
     *
     * @param createTime the value for ticket.create_time
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.modify_time
     *
     * @return the value of ticket.modify_time
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.modify_time
     *
     * @param modifyTime the value for ticket.modify_time
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.create_man
     *
     * @return the value of ticket.create_man
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.create_man
     *
     * @param createMan the value for ticket.create_man
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.modify_man
     *
     * @return the value of ticket.modify_man
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public String getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.modify_man
     *
     * @param modifyMan the value for ticket.modify_man
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan == null ? null : modifyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.remark
     *
     * @return the value of ticket.remark
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.remark
     *
     * @param remark the value for ticket.remark
     *
     * @mbggenerated Tue Oct 30 14:56:24 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}