package com.honglu.quickcall.account.facade.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CustomerSkill {
    private Long userSkillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.certify_id
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Long certifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.customer_id
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.skill_item_id
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Long skillItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.product_name
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.service_unit
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private String serviceUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.product_price
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.audit_status
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Byte auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.product_status
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Byte productStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.receive_status
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Byte receiveStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.discount_rate
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private BigDecimal discountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.discount_price
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private BigDecimal discountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.monday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Byte monday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.tuesday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Byte tuesday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.wednesday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Byte wednesday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.thursday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Byte thursday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.friday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Byte friday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.saturday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Byte saturday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.sunday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Byte sunday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.start_service_time
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Date startServiceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.end_service_time
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Date endServiceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.product_describe
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private String productDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.create_time
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.modify_time
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.create_man
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.modify_man
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private String modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_skill.remark
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.user_skill_id
     *
     * @return the value of customer_skill.user_skill_id
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Long getUserSkillId() {
        return userSkillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.user_skill_id
     *
     * @param userSkillId the value for customer_skill.user_skill_id
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setUserSkillId(Long userSkillId) {
        this.userSkillId = userSkillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.certify_id
     *
     * @return the value of customer_skill.certify_id
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Long getCertifyId() {
        return certifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.certify_id
     *
     * @param certifyId the value for customer_skill.certify_id
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setCertifyId(Long certifyId) {
        this.certifyId = certifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.customer_id
     *
     * @return the value of customer_skill.customer_id
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.customer_id
     *
     * @param customerId the value for customer_skill.customer_id
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.skill_item_id
     *
     * @return the value of customer_skill.skill_item_id
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Long getSkillItemId() {
        return skillItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.skill_item_id
     *
     * @param skillItemId the value for customer_skill.skill_item_id
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setSkillItemId(Long skillItemId) {
        this.skillItemId = skillItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.product_name
     *
     * @return the value of customer_skill.product_name
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.product_name
     *
     * @param productName the value for customer_skill.product_name
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.service_unit
     *
     * @return the value of customer_skill.service_unit
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public String getServiceUnit() {
        return serviceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.service_unit
     *
     * @param serviceUnit the value for customer_skill.service_unit
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setServiceUnit(String serviceUnit) {
        this.serviceUnit = serviceUnit == null ? null : serviceUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.product_price
     *
     * @return the value of customer_skill.product_price
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.product_price
     *
     * @param productPrice the value for customer_skill.product_price
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.audit_status
     *
     * @return the value of customer_skill.audit_status
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Byte getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.audit_status
     *
     * @param auditStatus the value for customer_skill.audit_status
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setAuditStatus(Byte auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.product_status
     *
     * @return the value of customer_skill.product_status
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Byte getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.product_status
     *
     * @param productStatus the value for customer_skill.product_status
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setProductStatus(Byte productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.receive_status
     *
     * @return the value of customer_skill.receive_status
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Byte getReceiveStatus() {
        return receiveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.receive_status
     *
     * @param receiveStatus the value for customer_skill.receive_status
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setReceiveStatus(Byte receiveStatus) {
        this.receiveStatus = receiveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.discount_rate
     *
     * @return the value of customer_skill.discount_rate
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public BigDecimal getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.discount_rate
     *
     * @param discountRate the value for customer_skill.discount_rate
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setDiscountRate(BigDecimal discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.discount_price
     *
     * @return the value of customer_skill.discount_price
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.discount_price
     *
     * @param discountPrice the value for customer_skill.discount_price
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.monday
     *
     * @return the value of customer_skill.monday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Byte getMonday() {
        return monday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.monday
     *
     * @param monday the value for customer_skill.monday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setMonday(Byte monday) {
        this.monday = monday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.tuesday
     *
     * @return the value of customer_skill.tuesday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Byte getTuesday() {
        return tuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.tuesday
     *
     * @param tuesday the value for customer_skill.tuesday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setTuesday(Byte tuesday) {
        this.tuesday = tuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.wednesday
     *
     * @return the value of customer_skill.wednesday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Byte getWednesday() {
        return wednesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.wednesday
     *
     * @param wednesday the value for customer_skill.wednesday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setWednesday(Byte wednesday) {
        this.wednesday = wednesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.thursday
     *
     * @return the value of customer_skill.thursday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Byte getThursday() {
        return thursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.thursday
     *
     * @param thursday the value for customer_skill.thursday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setThursday(Byte thursday) {
        this.thursday = thursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.friday
     *
     * @return the value of customer_skill.friday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Byte getFriday() {
        return friday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.friday
     *
     * @param friday the value for customer_skill.friday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setFriday(Byte friday) {
        this.friday = friday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.saturday
     *
     * @return the value of customer_skill.saturday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Byte getSaturday() {
        return saturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.saturday
     *
     * @param saturday the value for customer_skill.saturday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setSaturday(Byte saturday) {
        this.saturday = saturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.sunday
     *
     * @return the value of customer_skill.sunday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Byte getSunday() {
        return sunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.sunday
     *
     * @param sunday the value for customer_skill.sunday
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setSunday(Byte sunday) {
        this.sunday = sunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.start_service_time
     *
     * @return the value of customer_skill.start_service_time
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Date getStartServiceTime() {
        return startServiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.start_service_time
     *
     * @param startServiceTime the value for customer_skill.start_service_time
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setStartServiceTime(Date startServiceTime) {
        this.startServiceTime = startServiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.end_service_time
     *
     * @return the value of customer_skill.end_service_time
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Date getEndServiceTime() {
        return endServiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.end_service_time
     *
     * @param endServiceTime the value for customer_skill.end_service_time
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setEndServiceTime(Date endServiceTime) {
        this.endServiceTime = endServiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.product_describe
     *
     * @return the value of customer_skill.product_describe
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public String getProductDescribe() {
        return productDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.product_describe
     *
     * @param productDescribe the value for customer_skill.product_describe
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setProductDescribe(String productDescribe) {
        this.productDescribe = productDescribe == null ? null : productDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.create_time
     *
     * @return the value of customer_skill.create_time
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.create_time
     *
     * @param createTime the value for customer_skill.create_time
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.modify_time
     *
     * @return the value of customer_skill.modify_time
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.modify_time
     *
     * @param modifyTime the value for customer_skill.modify_time
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.create_man
     *
     * @return the value of customer_skill.create_man
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.create_man
     *
     * @param createMan the value for customer_skill.create_man
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.modify_man
     *
     * @return the value of customer_skill.modify_man
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public String getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.modify_man
     *
     * @param modifyMan the value for customer_skill.modify_man
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan == null ? null : modifyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_skill.remark
     *
     * @return the value of customer_skill.remark
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_skill.remark
     *
     * @param remark the value for customer_skill.remark
     *
     * @mbggenerated Fri Oct 19 11:34:05 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}