package com.honglu.quickcall.account.facade.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SkillItemExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_item_ext.id
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_item_ext.skill_item_id
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    private Long skillItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_item_ext.ext_type
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    private Byte extType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_item_ext.ext_value
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    private BigDecimal extValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_item_ext.create_time
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_item_ext.modify_time
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_item_ext.create_man
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_item_ext.modify_man
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    private String modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skill_item_ext.remark
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_item_ext.id
     *
     * @return the value of skill_item_ext.id
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_item_ext.id
     *
     * @param id the value for skill_item_ext.id
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_item_ext.skill_item_id
     *
     * @return the value of skill_item_ext.skill_item_id
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public Long getSkillItemId() {
        return skillItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_item_ext.skill_item_id
     *
     * @param skillItemId the value for skill_item_ext.skill_item_id
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public void setSkillItemId(Long skillItemId) {
        this.skillItemId = skillItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_item_ext.ext_type
     *
     * @return the value of skill_item_ext.ext_type
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public Byte getExtType() {
        return extType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_item_ext.ext_type
     *
     * @param extType the value for skill_item_ext.ext_type
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public void setExtType(Byte extType) {
        this.extType = extType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_item_ext.ext_value
     *
     * @return the value of skill_item_ext.ext_value
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public BigDecimal getExtValue() {
        return extValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_item_ext.ext_value
     *
     * @param extValue the value for skill_item_ext.ext_value
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public void setExtValue(BigDecimal extValue) {
        this.extValue = extValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_item_ext.create_time
     *
     * @return the value of skill_item_ext.create_time
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_item_ext.create_time
     *
     * @param createTime the value for skill_item_ext.create_time
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_item_ext.modify_time
     *
     * @return the value of skill_item_ext.modify_time
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_item_ext.modify_time
     *
     * @param modifyTime the value for skill_item_ext.modify_time
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_item_ext.create_man
     *
     * @return the value of skill_item_ext.create_man
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_item_ext.create_man
     *
     * @param createMan the value for skill_item_ext.create_man
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_item_ext.modify_man
     *
     * @return the value of skill_item_ext.modify_man
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public String getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_item_ext.modify_man
     *
     * @param modifyMan the value for skill_item_ext.modify_man
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan == null ? null : modifyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skill_item_ext.remark
     *
     * @return the value of skill_item_ext.remark
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skill_item_ext.remark
     *
     * @param remark the value for skill_item_ext.remark
     *
     * @mbggenerated Fri Oct 19 11:06:18 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}