package com.honglu.quickcall.task.dao;

import java.util.List;

import com.honglu.quickcall.task.entity.FadeCustomer;
import com.honglu.quickcall.task.entity.Skill;
import com.honglu.quickcall.task.entity.SkillExample;
import org.apache.ibatis.annotations.Param;

public interface SkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Oct 18 16:23:07 CST 2018
     */
    int countByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Oct 18 16:23:07 CST 2018
     */
    int deleteByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Oct 18 16:23:07 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Oct 18 16:23:07 CST 2018
     */
    int insert(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Oct 18 16:23:07 CST 2018
     */
    int insertSelective(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Oct 18 16:23:07 CST 2018
     */
    List<Skill> selectByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Oct 18 16:23:07 CST 2018
     */
    Skill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Oct 18 16:23:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") Skill record, @Param("example") SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Oct 18 16:23:07 CST 2018
     */
    int updateByExample(@Param("record") Skill record, @Param("example") SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Oct 18 16:23:07 CST 2018
     */
    int updateByPrimaryKeySelective(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbggenerated Thu Oct 18 16:23:07 CST 2018
     */
    int updateByPrimaryKey(Skill record);

    /**
     * 跳过 index条数据，查询一条数据
     * @param index
     * @return
     */
    Skill selectOneSkipNum(@Param("index") int index);
}