package com.honglu.quickcall.task.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.honglu.quickcall.task.entity.SkillItem;
import com.honglu.quickcall.task.entity.example.SkillItemExample;

@Mapper
public interface SkillItemMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table skill_item
	 *
	 * @mbggenerated Fri Oct 19 17:36:16 CST 2018
	 */
	int countByExample(SkillItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table skill_item
	 *
	 * @mbggenerated Fri Oct 19 17:36:16 CST 2018
	 */
	int deleteByExample(SkillItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table skill_item
	 *
	 * @mbggenerated Fri Oct 19 17:36:16 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table skill_item
	 *
	 * @mbggenerated Fri Oct 19 17:36:16 CST 2018
	 */
	int insert(SkillItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table skill_item
	 *
	 * @mbggenerated Fri Oct 19 17:36:16 CST 2018
	 */
	int insertSelective(SkillItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table skill_item
	 *
	 * @mbggenerated Fri Oct 19 17:36:16 CST 2018
	 */
	List<SkillItem> selectByExample(SkillItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table skill_item
	 *
	 * @mbggenerated Fri Oct 19 17:36:16 CST 2018
	 */
	SkillItem selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table skill_item
	 *
	 * @mbggenerated Fri Oct 19 17:36:16 CST 2018
	 */
	int updateByExampleSelective(@Param("record") SkillItem record, @Param("example") SkillItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table skill_item
	 *
	 * @mbggenerated Fri Oct 19 17:36:16 CST 2018
	 */
	int updateByPrimaryKeySelective(SkillItem record);

	/**
	 * 跳过 index条数据，查询一条数据
	 * 
	 * @param index
	 * @return
	 */
	SkillItem selectOneSkipNum(@Param("index") int index);

	/**
	 * 根据技能Id查询一项技能的价格
	 * 
	 * @param skillId
	 * @return
	 */
	BigDecimal selectOneSkillPrice(@Param("skillId") Long skillId);
}