package com.calf.module.appconfig.entity;

public class Advertisement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.id
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.title
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.name
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.ad_describle
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String adDescrible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.type
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.ad_status
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private Integer adStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.image_url
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.url
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.app_version
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String appVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.start_time
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.end_time
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.create_time
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.modify_time
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.create_man
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.modify_man
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String modifyMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.remark
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    private String remark;

    private String  appVersionIdList;

    private String  appVersionId;

    public String getAppVersionId() {
        return appVersionId;
    }

    public void setAppVersionId(String appVersionId) {
        this.appVersionId = appVersionId;
    }

    public String getAppVersionIdList() {
        return appVersionIdList;
    }

    public void setAppVersionIdList(String appVersionIdList) {
        this.appVersionIdList = appVersionIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.id
     *
     * @return the value of advertisement.id
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.id
     *
     * @param id the value for advertisement.id
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.title
     *
     * @return the value of advertisement.title
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.title
     *
     * @param title the value for advertisement.title
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.name
     *
     * @return the value of advertisement.name
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.name
     *
     * @param name the value for advertisement.name
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ad_describle
     *
     * @return the value of advertisement.ad_describle
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getAdDescrible() {
        return adDescrible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ad_describle
     *
     * @param adDescrible the value for advertisement.ad_describle
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setAdDescrible(String adDescrible) {
        this.adDescrible = adDescrible == null ? null : adDescrible.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.type
     *
     * @return the value of advertisement.type
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.type
     *
     * @param type the value for advertisement.type
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ad_status
     *
     * @return the value of advertisement.ad_status
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public Integer getAdStatus() {
        return adStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ad_status
     *
     * @param adStatus the value for advertisement.ad_status
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setAdStatus(Integer adStatus) {
        this.adStatus = adStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.image_url
     *
     * @return the value of advertisement.image_url
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.image_url
     *
     * @param imageUrl the value for advertisement.image_url
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.url
     *
     * @return the value of advertisement.url
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.url
     *
     * @param url the value for advertisement.url
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.app_version
     *
     * @return the value of advertisement.app_version
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.app_version
     *
     * @param appVersion the value for advertisement.app_version
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.start_time
     *
     * @return the value of advertisement.start_time
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.start_time
     *
     * @param startTime the value for advertisement.start_time
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.end_time
     *
     * @return the value of advertisement.end_time
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.end_time
     *
     * @param endTime the value for advertisement.end_time
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.create_time
     *
     * @return the value of advertisement.create_time
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.create_time
     *
     * @param createTime the value for advertisement.create_time
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.modify_time
     *
     * @return the value of advertisement.modify_time
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.modify_time
     *
     * @param modifyTime the value for advertisement.modify_time
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.create_man
     *
     * @return the value of advertisement.create_man
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.create_man
     *
     * @param createMan the value for advertisement.create_man
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.modify_man
     *
     * @return the value of advertisement.modify_man
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.modify_man
     *
     * @param modifyMan the value for advertisement.modify_man
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan == null ? null : modifyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.remark
     *
     * @return the value of advertisement.remark
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.remark
     *
     * @param remark the value for advertisement.remark
     *
     * @mbggenerated Thu Oct 25 10:19:53 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}