package com.honglu.quickcall.task.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TradeDetail {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column trade_detail.trade_id
	 *
	 * @mbggenerated
	 */
	private Long tradeId;

	private Long orderNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column trade_detail.out_price
	 *
	 * @mbggenerated
	 */
	private BigDecimal outPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column trade_detail.in_price
	 *
	 * @mbggenerated
	 */
	private BigDecimal inPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column trade_detail.type
	 *
	 * @mbggenerated
	 */
	private Integer type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column trade_detail.customer_id
	 *
	 * @mbggenerated
	 */
	private Long customerId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column trade_detail.trade_describe
	 *
	 * @mbggenerated
	 */
	private String tradeDescribe;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column trade_detail.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column trade_detail.modify_time
	 *
	 * @mbggenerated
	 */
	private Date modifyTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column trade_detail.create_man
	 *
	 * @mbggenerated
	 */
	private String createMan;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column trade_detail.modify_man
	 *
	 * @mbggenerated
	 */
	private String modifyMan;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column trade_detail.remark
	 *
	 * @mbggenerated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column trade_detail.trade_id
	 *
	 * @return the value of trade_detail.trade_id
	 *
	 * @mbggenerated
	 */
	public Long getTradeId() {
		return tradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column trade_detail.trade_id
	 *
	 * @param tradeId
	 *            the value for trade_detail.trade_id
	 *
	 * @mbggenerated
	 */
	public void setTradeId(Long tradeId) {
		this.tradeId = tradeId;
	}

	public Long getOrderNo() {
		return orderNo;
	}

	public void setOrderNo(Long orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column trade_detail.out_price
	 *
	 * @return the value of trade_detail.out_price
	 *
	 * @mbggenerated
	 */
	public BigDecimal getOutPrice() {
		return outPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column trade_detail.out_price
	 *
	 * @param outPrice
	 *            the value for trade_detail.out_price
	 *
	 * @mbggenerated
	 */
	public void setOutPrice(BigDecimal outPrice) {
		this.outPrice = outPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column trade_detail.in_price
	 *
	 * @return the value of trade_detail.in_price
	 *
	 * @mbggenerated
	 */
	public BigDecimal getInPrice() {
		return inPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column trade_detail.in_price
	 *
	 * @param inPrice
	 *            the value for trade_detail.in_price
	 *
	 * @mbggenerated
	 */
	public void setInPrice(BigDecimal inPrice) {
		this.inPrice = inPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column trade_detail.type
	 *
	 * @return the value of trade_detail.type
	 *
	 * @mbggenerated
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column trade_detail.type
	 *
	 * @param type
	 *            the value for trade_detail.type
	 *
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column trade_detail.customer_id
	 *
	 * @return the value of trade_detail.customer_id
	 *
	 * @mbggenerated
	 */
	public Long getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column trade_detail.customer_id
	 *
	 * @param customerId
	 *            the value for trade_detail.customer_id
	 *
	 * @mbggenerated
	 */
	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column trade_detail.trade_describe
	 *
	 * @return the value of trade_detail.trade_describe
	 *
	 * @mbggenerated
	 */
	public String getTradeDescribe() {
		return tradeDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column trade_detail.trade_describe
	 *
	 * @param tradeDescribe
	 *            the value for trade_detail.trade_describe
	 *
	 * @mbggenerated
	 */
	public void setTradeDescribe(String tradeDescribe) {
		this.tradeDescribe = tradeDescribe == null ? null : tradeDescribe.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column trade_detail.create_time
	 *
	 * @return the value of trade_detail.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column trade_detail.create_time
	 *
	 * @param createTime
	 *            the value for trade_detail.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column trade_detail.modify_time
	 *
	 * @return the value of trade_detail.modify_time
	 *
	 * @mbggenerated
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column trade_detail.modify_time
	 *
	 * @param modifyTime
	 *            the value for trade_detail.modify_time
	 *
	 * @mbggenerated
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column trade_detail.create_man
	 *
	 * @return the value of trade_detail.create_man
	 *
	 * @mbggenerated
	 */
	public String getCreateMan() {
		return createMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column trade_detail.create_man
	 *
	 * @param createMan
	 *            the value for trade_detail.create_man
	 *
	 * @mbggenerated
	 */
	public void setCreateMan(String createMan) {
		this.createMan = createMan == null ? null : createMan.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column trade_detail.modify_man
	 *
	 * @return the value of trade_detail.modify_man
	 *
	 * @mbggenerated
	 */
	public String getModifyMan() {
		return modifyMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column trade_detail.modify_man
	 *
	 * @param modifyMan
	 *            the value for trade_detail.modify_man
	 *
	 * @mbggenerated
	 */
	public void setModifyMan(String modifyMan) {
		this.modifyMan = modifyMan == null ? null : modifyMan.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column trade_detail.remark
	 *
	 * @return the value of trade_detail.remark
	 *
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column trade_detail.remark
	 *
	 * @param remark
	 *            the value for trade_detail.remark
	 *
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}