package com.calf.module.customer.entity;

import java.util.Date;

public class FadeCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fade_customer.id
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fade_customer.nick_name
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    private String nickName;

    private String headPortraitUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fade_customer.status
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fade_customer.remark
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fade_customer.create_time
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fade_customer.modify_time
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fade_customer.create_man
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fade_customer.modify_man
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    private String modifyMan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fade_customer.id
     *
     * @return the value of fade_customer.id
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fade_customer.id
     *
     * @param id the value for fade_customer.id
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fade_customer.nick_name
     *
     * @return the value of fade_customer.nick_name
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fade_customer.nick_name
     *
     * @param nickName the value for fade_customer.nick_name
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    public String getHeadPortraitUrl() {
        return headPortraitUrl;
    }

    public void setHeadPortraitUrl(String headPortraitUrl) {
        this.headPortraitUrl = headPortraitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fade_customer.status
     *
     * @return the value of fade_customer.status
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fade_customer.status
     *
     * @param status the value for fade_customer.status
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fade_customer.remark
     *
     * @return the value of fade_customer.remark
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fade_customer.remark
     *
     * @param remark the value for fade_customer.remark
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fade_customer.create_time
     *
     * @return the value of fade_customer.create_time
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fade_customer.create_time
     *
     * @param createTime the value for fade_customer.create_time
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fade_customer.modify_time
     *
     * @return the value of fade_customer.modify_time
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fade_customer.modify_time
     *
     * @param modifyTime the value for fade_customer.modify_time
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fade_customer.create_man
     *
     * @return the value of fade_customer.create_man
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fade_customer.create_man
     *
     * @param createMan the value for fade_customer.create_man
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fade_customer.modify_man
     *
     * @return the value of fade_customer.modify_man
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public String getModifyMan() {
        return modifyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fade_customer.modify_man
     *
     * @param modifyMan the value for fade_customer.modify_man
     *
     * @mbggenerated Wed Oct 17 16:59:07 CST 2018
     */
    public void setModifyMan(String modifyMan) {
        this.modifyMan = modifyMan == null ? null : modifyMan.trim();
    }
}