package com.honglu.quickcall.user.service.dao;

import com.honglu.quickcall.user.facade.entity.AppShareConfig;
import com.honglu.quickcall.user.facade.entity.example.AppShareConfigExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AppShareConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    int countByExample(AppShareConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    int deleteByExample(AppShareConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    int insert(AppShareConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    int insertSelective(AppShareConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    List<AppShareConfig> selectByExample(AppShareConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    AppShareConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") AppShareConfig record, @Param("example") AppShareConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    int updateByExample(@Param("record") AppShareConfig record, @Param("example") AppShareConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    int updateByPrimaryKeySelective(AppShareConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    int updateByPrimaryKey(AppShareConfig record);
}