package com.honglu.quickcall.user.service.dao;

import com.honglu.quickcall.user.facade.entity.AppShareConfig;
import com.honglu.quickcall.user.facade.entity.example.AppShareConfigExample;

import java.util.List;

public interface AppShareConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    int countByExample(AppShareConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share_config
     *
     * @mbggenerated Thu Oct 25 23:40:56 CST 2018
     */
    List<AppShareConfig> selectByExample(AppShareConfigExample example);

}