package com.honglu.quickcall.user.service.dao;

import java.util.List;

import com.honglu.quickcall.user.facade.entity.BigvScore;
import com.honglu.quickcall.user.facade.entity.example.BigvScoreExample;
import org.apache.ibatis.annotations.Param;

public interface BigvScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigv_score
     *
     * @mbggenerated Thu Oct 25 14:43:38 CST 2018
     */
    int countByExample(BigvScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigv_score
     *
     * @mbggenerated Thu Oct 25 14:43:38 CST 2018
     */
    int deleteByExample(BigvScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigv_score
     *
     * @mbggenerated Thu Oct 25 14:43:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigv_score
     *
     * @mbggenerated Thu Oct 25 14:43:38 CST 2018
     */
    int insert(BigvScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigv_score
     *
     * @mbggenerated Thu Oct 25 14:43:38 CST 2018
     */
    int insertSelective(BigvScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigv_score
     *
     * @mbggenerated Thu Oct 25 14:43:38 CST 2018
     */
    List<BigvScore> selectByExample(BigvScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigv_score
     *
     * @mbggenerated Thu Oct 25 14:43:38 CST 2018
     */
    BigvScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigv_score
     *
     * @mbggenerated Thu Oct 25 14:43:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") BigvScore record, @Param("example") BigvScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigv_score
     *
     * @mbggenerated Thu Oct 25 14:43:38 CST 2018
     */
    int updateByExample(@Param("record") BigvScore record, @Param("example") BigvScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigv_score
     *
     * @mbggenerated Thu Oct 25 14:43:38 CST 2018
     */
    int updateByPrimaryKeySelective(BigvScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bigv_score
     *
     * @mbggenerated Thu Oct 25 14:43:38 CST 2018
     */
    int updateByPrimaryKey(BigvScore record);
}