package com.honglu.quickcall.user.service.dao;


import com.honglu.quickcall.user.facade.entity.Blacklist;

public interface BlacklistMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    int insert(Blacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    int insertSelective(Blacklist record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    Blacklist selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    int updateByPrimaryKeySelective(Blacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbggenerated Sun Oct 21 19:35:51 CST 2018
     */
    int updateByPrimaryKey(Blacklist record);
}